{% set name = "pyCompare" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a848ceb39ba4c0a3958a080705e1630b5624ba84275b598a240bafd6ef2313c6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.14.2
    - scipy >=1.0.1
    - matplotlib-base >=3.0.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyCompare

about:
  home: https://github.com/jaketmp/pyCompare
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python module for generating Bland-Altman plots to compare two sets of measurements.

extra:
  recipe-maintainers:
    - hoechenberger
