{% set name = "pyCompare" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df69b06c95294a7476d321a2076fb0b5b7cf930ef433ae86119d5067116ecb5e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.14.2
    - scipy >=1.0.1
    - matplotlib-base >=3.0.2

test:
  imports:
    - pyCompare

about:
  home: https://github.com/jaketmp/pyCompare
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python module for generating Bland-Altman plots to compare two sets of measurements.

extra:
  recipe-maintainers:
    - hoechenberger
